### ISSUE TITLE
Fix isOdd method

### ISSUE THREAD

**Issue by abhigyank** [BlakeGuilloud/ganon#129] opened 2017-10-19 10:28 UTC
There is currently a method called `isOdd` that lives in `/lib/isOdd.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test isOdd` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

**Comment by abhigyank** [comment] 2017-10-19 10:28
@BlakeGuilloud Assign this to me please!

**Comment by andreasgruenh** [comment] 2017-10-19 10:33
Thanks for your contribution! The issue is reserved for you for 24 hours. After that any pull request that implements this will be merged :)

**Closed** 2017-10-19 11:40 UTC
Labels: Great for beginners!, hacktoberfest, in progress
